# -*- coding: utf-8 -*-
"""feature engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0edZglayGfYXCjG0UImkK_mqpKOryi4

# Task
Practice feature engineering by creating meaningful features from raw data to improve predictive power.

## Load the data

### Subtask:
Load the `train.csv` and `test.csv` datasets into pandas DataFrames.

**Reasoning**:
Import pandas and load the train and test datasets into dataframes.
"""

import pandas as pd

train_df = pd.read_csv('/content/train.csv')
test_df = pd.read_csv('/content/test.csv')

"""## Explore the data

### Subtask:
Display the first few rows, data types, and missing values for both DataFrames.

**Reasoning**:
Display the first few rows, data types, and missing values for both train_df and test_df DataFrames.
"""

import matplotlib.pyplot as plt
import seaborn as sns

print("Train DataFrame:")
display(train_df.head())
print("\nTrain DataFrame Info:")
train_df.info()
print("\nTrain DataFrame Missing Values:")
print(train_df.isnull().sum())

print("\nTest DataFrame:")
display(test_df.head())
print("\nTest DataFrame Info:")
test_df.info()
print("\nTest DataFrame Missing Values:")
print(test_df.isnull().sum())

"""-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-
"""

import matplotlib.pyplot as plt
import seaborn as sns

print("\nEDA Plots:")

plt.figure(figsize=(2, 2))
sns.countplot(x='Survived', data=train_df)
plt.title('Distribution of Survival')
plt.tight_layout()
plt.show()
plt.close() # Close the plot

plt.figure(figsize=(2, 2))
sns.barplot(x='Pclass', y='Survived', data=train_df)
plt.title('Survival Rate by Pclass')
plt.ylabel('Survival Rate')
plt.tight_layout()
plt.show()
plt.close() # Close the plot

plt.figure(figsize=(2, 2))
sns.histplot(train_df['Age'].dropna(), bins=30, kde=True)
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
plt.close() # Close the plot

plt.figure(figsize=(2, 2))
sns.histplot(train_df['Fare'].dropna(), bins=30, kde=True)
plt.title('Distribution of Fare')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
plt.close() # Close the plot

"""## Handle missing values

### Subtask:
Impute missing 'Age' values with the median and fill missing 'Embarked' values with the most frequent category in the training data.

**Reasoning**:
Impute missing 'Age' values with the median and fill missing 'Embarked' values with the most frequent category in the training data. Also, fill the missing 'Fare' value in the test data.
"""

# Calculate the median of the 'Age' column in the train_df DataFrame.
median_age = train_df['Age'].median()

# Fill the missing values in the 'Age' column of both train_df and test_df DataFrames with the calculated median.
train_df['Age'] = train_df['Age'].fillna(median_age)
test_df['Age'] = test_df['Age'].fillna(median_age)

# Calculate the most frequent value (mode) of the 'Embarked' column in the train_df DataFrame.
most_frequent_embarked = train_df['Embarked'].mode()[0]

# Fill the missing values in the 'Embarked' column of the train_df DataFrame with the calculated mode.
train_df['Embarked'] = train_df['Embarked'].fillna(most_frequent_embarked)

# Fill the single missing 'Fare' value in the test_df with the median 'Fare' from the train_df.
median_fare_train = train_df['Fare'].median()
test_df['Fare'] = test_df['Fare'].fillna(median_fare_train)

print("Missing values after imputation in train_df:")
print(train_df.isnull().sum())

print("\nMissing values after imputation in test_df:")
print(test_df.isnull().sum())

"""## Create new features

### Subtask:
Create 'FamilySize' and 'IsAlone' features, extract 'Title' from the 'Name' column, bin 'Age' into categories, and convert 'Fare' into quartiles.

**Reasoning**:
Implement all the feature engineering steps: create FamilySize and IsAlone features, extract and process the Title, bin Age into categories, and convert Fare into quartiles.
"""

# 1. Create 'FamilySize' column
train_df['FamilySize'] = train_df['SibSp'] + train_df['Parch'] + 1
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch'] + 1

# 2. Create 'IsAlone' column
train_df['IsAlone'] = 1
test_df['IsAlone'] = 1
train_df.loc[train_df['FamilySize'] > 1, 'IsAlone'] = 0
test_df.loc[test_df['FamilySize'] > 1, 'IsAlone'] = 0

# 3. Extract 'Title' from 'Name'
train_df['Title'] = train_df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)
test_df['Title'] = test_df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

# 4. Replace less frequent titles with 'Rare'
for df in [train_df, test_df]:
    df['Title'] = df['Title'].replace(['Lady', 'Countess', 'Capt', 'Col', 'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
    df['Title'] = df['Title'].replace('Mlle', 'Miss')
    df['Title'] = df['Title'].replace('Ms', 'Miss')
    df['Title'] = df['Title'].replace('Mme', 'Mrs')

# 5. Bin 'Age' into categories
train_df['AgeBand'] = pd.cut(train_df['Age'], 5)
test_df['AgeBand'] = pd.cut(test_df['Age'], 5)

# 6. Create 'FareBand' by converting 'Fare' into quartiles
test_df['Fare'] = test_df['Fare'].fillna(test_df['Fare'].median()) # Ensure no missing values in Fare before qcut
train_df['FareBand'] = pd.qcut(train_df['Fare'], 4)
test_df['FareBand'] = pd.qcut(test_df['Fare'], 4)


print("Train DataFrame after feature engineering:")
display(train_df.head())
print("\nTest DataFrame after feature engineering:")
display(test_df.head())
print("\nTrain DataFrame 'Title' distribution:")
print(train_df['Title'].value_counts())
print("\nTest DataFrame 'Title' distribution:")
print(test_df['Title'].value_counts())
print("\nTrain DataFrame 'AgeBand' distribution:")
print(train_df['AgeBand'].value_counts())
print("\nTest DataFrame 'AgeBand' distribution:")
print(test_df['AgeBand'].value_counts())
print("\nTrain DataFrame 'FareBand' distribution:")
print(train_df['FareBand'].value_counts())
print("\nTest DataFrame 'FareBand' distribution:")
print(test_df['FareBand'].value_counts())

"""## Encode categorical variables

### Subtask:
Use one-hot encoding for 'Sex', 'Embarked', and 'Title'.

**Reasoning**:
Select the columns for one-hot encoding, apply one-hot encoding, concatenate the new columns, and drop the original columns. Finally, display the heads of the modified dataframes.
"""

# Select columns for one-hot encoding
cols_to_encode = ['Sex', 'Embarked', 'Title']

# Apply one-hot encoding
train_encoded = pd.get_dummies(train_df[cols_to_encode], prefix=cols_to_encode)
test_encoded = pd.get_dummies(test_df[cols_to_encode], prefix=cols_to_encode)

# Align columns - this is crucial to ensure both dataframes have the same columns
train_encoded, test_encoded = train_encoded.align(test_encoded, join='outer', axis=1, fill_value=0)


# Concatenate encoded columns with original dataframes and drop original columns
train_df = pd.concat([train_df.drop(cols_to_encode, axis=1), train_encoded], axis=1)
test_df = pd.concat([test_df.drop(cols_to_encode, axis=1), test_encoded], axis=1)

# Display the head of the modified dataframes
print("Train DataFrame after one-hot encoding:")
display(train_df.head())
print("\nTest DataFrame after one-hot encoding:")
display(test_df.head())

"""## Prepare data for modeling

### Subtask:
Separate features and target variable for the training data and ensure consistency between training and testing data after feature engineering and encoding.

**Reasoning**:
Separate the target variable and features for the training data and select the relevant features for both training and testing datasets, then align the columns.
"""

# Define the target variable for the training data
y_train = train_df['Survived']

# Define the features for the training data, dropping irrelevant columns
X_train = train_df.drop(['Survived', 'PassengerId', 'Name', 'Ticket', 'Cabin', 'AgeBand', 'FareBand', 'SibSp', 'Parch'], axis=1)

# Define the features for the testing data, dropping the same irrelevant columns
X_test = test_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin', 'AgeBand', 'FareBand', 'SibSp', 'Parch'], axis=1)

# Align the columns of X_train and X_test to ensure consistency
X_train, X_test = X_train.align(X_test, join='inner', axis=1)

# Display the head of the resulting feature and target dataframes
print("X_train head:")
display(X_train.head())
print("\ny_train head:")
display(y_train.head())
print("\nX_test head:")
display(X_test.head())

"""## Train and compare models

### Subtask:
Train a Logistic Regression model on the original features, train a Logistic Regression model on the engineered features, and compare the accuracy of the two models.

**Reasoning**:
Train Logistic Regression models on both original and engineered features and compare their accuracy on the training data.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Create a copy of the original training and testing dataframes before feature engineering and encoding
train_df_original = pd.read_csv('/content/train.csv')
test_df_original = pd.read_csv('/content/test.csv')

# Handle missing values in the original dataframes as done previously
median_age_original = train_df_original['Age'].median()
train_df_original['Age'] = train_df_original['Age'].fillna(median_age_original)
test_df_original['Age'] = test_df_original['Age'].fillna(median_age_original)
most_frequent_embarked_original = train_df_original['Embarked'].mode()[0]
train_df_original['Embarked'] = train_df_original['Embarked'].fillna(most_frequent_embarked_original)
median_fare_test_original = test_df_original['Fare'].median()
test_df_original['Fare'] = test_df_original['Fare'].fillna(median_fare_test_original)

# Define features and target for original data
# Drop the same irrelevant columns except for 'Sex', 'Embarked', and 'Title' which are kept as original
X_train_original = train_df_original.drop(['Survived', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
y_train_original = train_df_original['Survived']
X_test_original = test_df_original.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)


# One-hot encode categorical features in the original dataframes for modeling
cols_to_encode_original = ['Sex', 'Embarked'] # Title is not in original dataframes, it was engineered
X_train_original = pd.get_dummies(X_train_original, columns=cols_to_encode_original, drop_first=True)
X_test_original = pd.get_dummies(X_test_original, columns=cols_to_encode_original, drop_first=True)

# Align columns after one-hot encoding
X_train_original, X_test_original = X_train_original.align(X_test_original, join='inner', axis=1)


# Train Logistic Regression model on original features
model_original = LogisticRegression(solver='liblinear')
model_original.fit(X_train_original, y_train_original)

# Make predictions on the training data using the original features model
y_pred_original = model_original.predict(X_train_original)

# Train Logistic Regression model on engineered features
# X_train and y_train are already prepared from previous steps
model_engineered = LogisticRegression(solver='liblinear')
model_engineered.fit(X_train, y_train)

# Make predictions on the training data using the engineered features model
y_pred_engineered = model_engineered.predict(X_train)

# Calculate accuracy for both models on the training data
accuracy_original = accuracy_score(y_train_original, y_pred_original)
accuracy_engineered = accuracy_score(y_train, y_pred_engineered)

# Print the accuracy scores
print(f"Accuracy of Logistic Regression on Original Features (Training Data): {accuracy_original:.4f}")
print(f"Accuracy of Logistic Regression on Engineered Features (Training Data): {accuracy_engineered:.4f}")