# -*- coding: utf-8 -*-
"""Finalproject_2376 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PQUJTGoaKessmAxvuLCFY_zKheZcxXu

# Intellectus – AI Research Assistant Agent
### ITAI 2376 – Deep Learning Artificial Intelligence  
**Group Name:** AI Alchemists  
**Members:** Ruben Valenzuela, Benjamin LaCount II, Daedra minigan

This notebook implements *Intellectus*, a research assistant agent that:
- Searches the web for a given topic  
- Reads and processes content from selected URLs  
- Stores information in a vector database (ChromaDB)  
- Uses Retrieval-Augmented Generation (RAG) to produce grounded summaries  
- Incorporates a simple reinforcement learning feedback mechanism  
- Applies safety and input validation to respect project constraints

## 1. Install dependencies

We install all required Python libraries for:
- Web search (`duckduckgo_search`)
- Web scraping (`requests`, `beautifulsoup4`)
- Vector database (`chromadb`)
- Embeddings and semantic similarity (`sentence-transformers`)
"""

import warnings

# Suppress DeprecationWarnings (including those from jupyter_client) to keep output clean
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore")

!pip install -q duckduckgo-search googlesearch-python wikipedia chromadb sentence-transformers beautifulsoup4 requests

"""## 2. Imports and global configuration

This cell imports all necessary modules and sets up:
- The embedding model
- The ChromaDB client and collection
- Basic configuration for the agent

"""

import re
import time
from typing import List, Dict, Any, Optional

import requests
from bs4 import BeautifulSoup

from duckduckgo_search import DDGS

import chromadb
from chromadb.utils import embedding_functions

from sentence_transformers import SentenceTransformer, util

"""## 3. Initialize embedding model and vector database (ChromaDB)

We use:
- `all-MiniLM-L6-v2` as a lightweight SentenceTransformer model
- An in-memory ChromaDB collection to store and retrieve document chunks

"""

# Embedding model for semantic similarity and summarization
embedding_model_name = "all-MiniLM-L6-v2"
sentence_model = SentenceTransformer(embedding_model_name)

# ChromaDB client & collection
chroma_client = chromadb.Client()

embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name=embedding_model_name
)

# Use get_or_create_collection to avoid errors if re-running the cell
collection = chroma_client.get_or_create_collection(
    name="intellectus_docs",
    embedding_function=embedding_fn
)

print("Embedding model and ChromaDB collection initialized.")

"""## 4. Safety and input validation

This helper checks whether a user query is within safe and allowed boundaries.
We:
- Block clearly harmful or inappropriate topics
- Enforce a basic scope (no detailed medical, financial, or illegal advice)

"""

class SafetyModule:
    def __init__(self):
        # Very simple keyword-based filter for demo purposes
        self.blocklist = [
            "suicide", "kill myself", "self harm", "bomb", "terrorist",
            "child sexual", "how to hack", "make a bomb", "murder"
        ]
        self.discouraged = [
            "diagnose me", "medical treatment", "which stock should I buy",
            "insider trading"
        ]

    def validate(self, query: str) -> (bool, str):
        q_lower = query.lower()

        for bad in self.blocklist:
            if bad in q_lower:
                return False, (
                    "This agent cannot assist with harmful, violent, "
                    "illegal or self-harm related topics."
                )

        for soft in self.discouraged:
            if soft in q_lower:
                return False, (
                    "This agent is not designed to provide personalized "
                    "medical, financial or legal advice."
                )

        return True, "OK"

safety_module = SafetyModule()
print("Safety module ready.")

"""## 5. Tool 1 – Web search (DuckDuckGo)

We implement a web search tool using `duckduckgo-search`.  
This satisfies the "Tool Integration" requirement for external information retrieval.

The agent will:
- Use this tool to get candidate URLs and snippets
- Later decide which URLs to read in detail

"""

import warnings
# Suppress DeprecationWarnings to ensure clean output in this cell
warnings.filterwarnings("ignore", category=DeprecationWarning)

class WebSearchTool:
    """
    Real search tool with multiple fallbacks: DuckDuckGo -> Google -> Wikipedia.
    """
    def __init__(self, max_results: int = 5):
        self.max_results = max_results
        self.ddgs = DDGS()

    def search(self, query: str) -> List[Dict[str, Any]]:
        results = []

        # --- Strategy 1: DuckDuckGo ---
        backends = ['api', 'html', 'lite']
        for backend in backends:
            try:
                # print(f"[WebSearchTool] Trying DDGS backend: {backend}...")
                ddg_results = list(self.ddgs.text(query, max_results=self.max_results, backend=backend))
                if ddg_results:
                    for r in ddg_results:
                        results.append({
                            "title": r.get("title", "No Title"),
                            "url": r.get("href", r.get("url", "")),
                            "snippet": r.get("body", r.get("snippet", ""))
                        })
                    break
            except Exception as e:
                continue

        if results:
            return results

        # --- Strategy 2: Google Search Fallback ---
        print("[WebSearchTool] DuckDuckGo returned no results. Switching to Google Search fallback...")
        try:
            from googlesearch import search as google_search
            # google_search returns a generator of URLs
            g_urls = list(google_search(query, num_results=self.max_results))

            for url in g_urls:
                results.append({
                    "title": "Google Search Result",
                    "url": url,
                    "snippet": "Result retrieved via Google Search fallback. Content will be extracted by the reader tool."
                })

        except ImportError:
            print("[WebSearchTool] 'googlesearch' library not found. Please install 'googlesearch-python'.")
        except Exception as e:
            print(f"[WebSearchTool] Google Search failed: {e}")

        if results:
            return results

        # --- Strategy 3: Wikipedia Fallback ---
        print("[WebSearchTool] Google Search also failed. Switching to Wikipedia fallback...")
        try:
            import wikipedia
            wikipedia.set_lang("en")
            wiki_titles = wikipedia.search(query, results=self.max_results)

            for title in wiki_titles:
                try:
                    page = wikipedia.page(title, auto_suggest=False)
                    results.append({
                        "title": page.title,
                        "url": page.url,
                        "snippet": page.summary[:300] + "..."
                    })
                except Exception:
                    continue
        except ImportError:
            print("[WebSearchTool] 'wikipedia' library not found. Please install 'wikipedia'.")
        except Exception as e:
            print(f"[WebSearchTool] Wikipedia failed: {e}")

        if not results:
            print("[WebSearchTool] All search backends failed.")

        return results


web_search_tool = WebSearchTool(max_results=5)
print("Web search tool initialized (DDGS + Google + Wikipedia).")

"""## 6. Tool 2 – Document reader and web scraper

Given a URL, this tool:
- Downloads the HTML
- Removes scripts, styles, navigation, etc.
- Extracts the visible text
- Truncates it to a reasonable length (for demo purposes)

This satisfies the "Document Processing" tool requirement.

"""

class DocumentReaderTool:
    def __init__(self, max_chars: int = 15000, timeout: int = 10):
        self.max_chars = max_chars
        self.timeout = timeout
        self.headers = {
            "User-Agent": "Mozilla/5.0 (Intellectus Research Agent)"
        }

    def fetch_and_clean(self, url: str) -> Dict[str, Any]:
        """Fetch URL content and return cleaned text."""
        try:
            resp = requests.get(url, headers=self.headers, timeout=self.timeout)
            resp.raise_for_status()
        except Exception as e:
            return {
                "url": url,
                "ok": False,
                "error": str(e),
                "text": ""
            }

        soup = BeautifulSoup(resp.text, "html.parser")

        # Remove non-content elements
        for tag in soup(["script", "style", "nav", "footer", "header", "noscript"]):
            tag.decompose()

        text = soup.get_text(separator=" ")
        # Normalize whitespace
        text = re.sub(r"\s+", " ", text).strip()
        text = text[:self.max_chars]

        return {
            "url": url,
            "ok": True,
            "error": "",
            "text": text
        }

doc_reader_tool = DocumentReaderTool()
print("Document reader tool initialized.")

"""## 7. Helper functions – Chunking and storing documents in ChromaDB

We:
- Split long texts into smaller chunks
- Store those chunks in a ChromaDB collection
- Attach simple metadata (source URL and chunk index)

"""

def chunk_text(text: str, max_tokens: int = 400) -> List[str]:
    """
    Very simple chunking based on approximate token-like word count.
    """
    words = text.split()
    chunks = []
    for i in range(0, len(words), max_tokens):
        chunk = " ".join(words[i:i + max_tokens])
        chunks.append(chunk)
    return chunks


def add_document_to_vector_store(doc: Dict[str, Any], topic: str):
    """
    Add scraped document text to ChromaDB as multiple chunks.
    """
    if not doc["ok"] or not doc["text"]:
        return

    chunks = chunk_text(doc["text"], max_tokens=200)
    ids = []
    metadatas = []
    documents = []

    for idx, ch in enumerate(chunks):
        ids.append(f"{doc['url']}_chunk_{idx}")
        metadatas.append({
            "url": doc["url"],
            "chunk_index": idx,
            "topic": topic
        })
        documents.append(ch)

    if documents:
        collection.add(
            ids=ids,
            metadatas=metadatas,
            documents=documents
        )
        print(f"Added {len(documents)} chunks from {doc['url']}")
    else:
        print(f"No chunks added for {doc['url']}")

"""## 8. Retrieval and semantic summarization

We implement:
- A retrieval function that queries ChromaDB for the most relevant chunks
- A simple extractive summarizer using `sentence-transformers` to pick
  the most relevant sentences given the user query.

"""

import torch

def retrieve_relevant_chunks(query: str, n_results: int = 5) -> List[str]:
    """
    Query the ChromaDB collection for the most relevant chunks.
    """
    try:
        results = collection.query(
            query_texts=[query],
            n_results=n_results
        )
        docs = results.get("documents", [[]])[0]
        return docs
    except Exception as e:
        print(f"[retrieve_relevant_chunks] Error: {e}")
        return []


def simple_extractive_summary(query: str,
                              chunks: List[str],
                              max_sentences: int = 6,
                              lambda_param: float = 0.6) -> str:
    """
    Uses Maximal Marginal Relevance (MMR) to select sentences for the summary.
    lambda_param controls the trade-off between relevance (1.0) and diversity (0.0).
    """
    if not chunks:
        return "No relevant content retrieved."

    # 1. Split chunks into sentences
    sentences = []
    for ch in chunks:
        # Simple split by sentence endings
        for s in re.split(r'(?<=[.!?])\s+', ch):
            s = s.strip()
            if len(s) > 40:  # Filter out very short fragments
                sentences.append(s)

    if not sentences:
        return "Not enough sentence-level content to summarize."

    # 2. Generate embeddings
    # Convert to tensor for efficient similarity calculation
    query_emb = sentence_model.encode(query, convert_to_tensor=True)
    sent_embs = sentence_model.encode(sentences, convert_to_tensor=True)

    # 3. Compute Similarities
    # Cosine similarity between query and all sentences
    query_sims = util.cos_sim(query_emb, sent_embs)[0]  # shape (num_sentences,)

    # Cosine similarity between all pairs of sentences
    sent_sims = util.cos_sim(sent_embs, sent_embs)      # shape (num_sentences, num_sentences)

    # 4. MMR Selection Loop
    selected_indices = []
    candidate_indices = list(range(len(sentences)))

    for _ in range(min(max_sentences, len(sentences))):
        best_score = -float('inf')
        best_idx = -1

        for idx in candidate_indices:
            # Relevance term
            relevance = query_sims[idx].item()

            # Redundancy term
            if not selected_indices:
                redundancy = 0.0
            else:
                # Max similarity to any already selected sentence
                # sent_sims[idx, selected_indices] extracts similarities for current candidate vs selected ones
                redundancy = torch.max(sent_sims[idx, selected_indices]).item()

            # MMR Formula
            mmr_score = lambda_param * relevance - (1 - lambda_param) * redundancy

            if mmr_score > best_score:
                best_score = mmr_score
                best_idx = idx

        if best_idx != -1:
            selected_indices.append(best_idx)
            candidate_indices.remove(best_idx)

    # 5. Sort indices to preserve original text flow
    selected_indices.sort()

    # 6. Construct summary
    final_sentences = [sentences[i] for i in selected_indices]
    summary = " ".join(final_sentences)

    return summary

"""## 9. Reinforcement learning – simple feedback mechanism

We implement a lightweight RL-inspired component:
- The user provides a feedback score (1–5)
- The agent updates internal configuration (e.g., how many results to fetch)
- Over time, this simulates policy improvement based on user preferences

"""

class FeedbackManager:
    def __init__(self):
        self.history = []
        # Simple "policy" parameters
        self.num_search_results = 5
        self.num_docs_to_read = 3

    def apply_feedback(self, score: int):
        """
        Update internal configuration based on feedback score.
        Higher scores => keep / slightly reduce resource usage.
        Lower scores => increase search breadth.
        """
        self.history.append(score)

        if score <= 2:
            # Results were poor → widen search
            self.num_search_results = min(self.num_search_results + 1, 8)
            self.num_docs_to_read = min(self.num_docs_to_read + 1,
                                        self.num_search_results)
        elif score >= 4:
            # Results were good → we might be able to do more with less
            self.num_search_results = max(self.num_search_results - 1, 3)

        print(f"[Feedback] Updated num_search_results={self.num_search_results}, "
              f"num_docs_to_read={self.num_docs_to_read}")

feedback_manager = FeedbackManager()
print("Feedback manager initialized.")

"""## 10. IntellectusAgent – ReAct-style reasoning and acting

The agent:
1. Validates the user input (safety)
2. Uses the web search tool to find candidate URLs
3. Reads and processes a subset of URLs
4. Stores content in the vector database
5. Retrieves the most relevant chunks
6. Generates an extractive summary
7. Returns a structured report

It follows a simple ReAct loop:
- Thought → Action → Observation (printed for transparency)

"""

import warnings
# Suppress DeprecationWarnings to ensure clean output in this cell
warnings.filterwarnings("ignore", category=DeprecationWarning)

class IntellectusAgent:
    def __init__(self,
                 web_tool: WebSearchTool,
                 reader_tool: DocumentReaderTool,
                 feedback_mgr: FeedbackManager,
                 safety: SafetyModule):
        self.web_tool = web_tool
        self.reader_tool = reader_tool
        self.feedback_mgr = feedback_mgr
        self.safety = safety

    def run(self, query: str) -> Dict[str, Any]:
        report = {
            "query": query,
            "status": "ok",
            "messages": [],
            "sources": [],
            "summary": ""
        }

        # 1. Safety check
        ok, msg = self.safety.validate(query)
        if not ok:
            report["status"] = "blocked"
            report["messages"].append(f"[Safety] {msg}")
            print(f"[Safety] {msg}")
            return report

        print(f"[Thought] I need to find sources for: '{query}'")
        report["messages"].append(
            "[Thought] I need to find sources for this topic."
        )

        # 2. Web search
        print("[Action] Calling WebSearchTool...")
        results = self.web_tool.search(query)
        if not results:
            report["status"] = "no_results"
            report["messages"].append(
                "[Observation] No results found from web search."
            )
            return report

        print(f"[Observation] Retrieved {len(results)} search results.")
        report["messages"].append(
            f"[Observation] Retrieved {len(results)} search results."
        )

        # 3. Read top N documents based on feedback policy
        num_to_read = min(
            self.feedback_mgr.num_docs_to_read,
            len(results)
        )
        print(f"[Thought] I will read the top {num_to_read} URLs.")
        report["messages"].append(
            f"[Thought] I will read the top {num_to_read} URLs."
        )

        for r in results[:num_to_read]:
            url = r["url"]
            print(f"[Action] Reading URL: {url}")
            doc = self.reader_tool.fetch_and_clean(url)
            if doc["ok"]:
                add_document_to_vector_store(doc, topic=query)
                report["sources"].append(url)
            else:
                print(f"[Observation] Failed to read {url}: {doc['error']}")
                report["messages"].append(
                    f"[Observation] Failed to read {url}."
                )

        # 4. Retrieve from vector store (UPDATED to 10 chunks)
        print("[Action] Retrieving relevant chunks from ChromaDB...")
        chunks = retrieve_relevant_chunks(query, n_results=10)
        print(f"[Observation] Retrieved {len(chunks)} chunks for summarization.")
        report["messages"].append(
            f"[Observation] Retrieved {len(chunks)} chunks for summarization."
        )

        # 5. Summarize
        print("[Thought] I will summarize the main points grounded in these chunks.")
        summary = simple_extractive_summary(query, chunks, max_sentences=6)
        report["summary"] = summary

        return report

# Initialize the agent instance before using it
agent = IntellectusAgent(
    web_tool=web_search_tool,
    reader_tool=doc_reader_tool,
    feedback_mgr=feedback_manager,
    safety=safety_module
)

print("Intellectus agent initialized.")

"""## 11. Demo – Run Intellectus on an example research query

We now:
1. Ask the user for a research topic
2. Run the Intellectus agent
3. Display the resulting structured report

"""

import warnings
# Suppress DeprecationWarnings to ensure clean output in this cell
warnings.filterwarnings("ignore", category=DeprecationWarning)

example_query = "Benefits of strength training for mental health"

# Ensure agent is initialized (in case previous cells weren't run in order)
if 'agent' not in globals():
    agent = IntellectusAgent(
        web_tool=web_search_tool,
        reader_tool=doc_reader_tool,
        feedback_mgr=feedback_manager,
        safety=safety_module
    )

report = agent.run(example_query)

print("\n=== INTELLECTUS REPORT ===")
print(f"Query: {report['query']}")
print(f"Status: {report['status']}\n")

print("Top Sources:")
for s in report["sources"]:
    print(" -", s)

print("\nSummary:")
print(report["summary"][:2000])  # truncate just in case

"""## 12. User feedback (RL element) and second run

We simulate user feedback:
- The user rates how helpful the summary was (1–5)
- The feedback manager updates the internal policy parameters
- We can then run the agent again and observe changes

"""

# Simulate feedback (for demo we can also change this manually)
user_score = 4  # pretend the user gave a 4/5 rating

print(f"\n[User] Feedback score: {user_score}")
feedback_manager.apply_feedback(user_score)

# Optionally, run another query to see the updated policy in action
second_query = "Impacts of social media on teenagers"
second_report = agent.run(second_query)

print("\n=== SECOND INTELLECTUS REPORT ===")
print(f"Query: {second_report['query']}")
print(f"Status: {second_report['status']}\n")

print("Top Sources:")
for s in second_report["sources"]:
    print(" -", s)

print("\nSummary:")
print(second_report["summary"][:2000])

# ============================================
# 🟦 USER INTERACTIVE QUERY – FINAL DEMO CELL
# ============================================
import textwrap
import warnings

# Ensure warnings are filtered for this interaction
warnings.filterwarnings("ignore", category=DeprecationWarning)

print("🔎 Welcome to Intellectus – AI Research Assistant")
print("Type any research topic you want to explore.\n")

# Ask user for a topic
user_query = input("Enter your research topic: ")

# Run the agent
print("\nRunning Intellectus...\n")
user_report = agent.run(user_query)

# Print results
print("\n=== INTELLECTUS REPORT ===")
print(f"Query: {user_report['query']}")
print(f"Status: {user_report['status']}\n")

print("Top Sources:")
if user_report["sources"]:
    for s in user_report["sources"]:
        print(" -", s)
else:
    print("No valid sources found.")

print("\nSummary:")
summary_text = user_report["summary"]
# Wrap text for better readability (width=80)
wrapped_summary = textwrap.fill(summary_text, width=80)
print(wrapped_summary)


# Optional feedback
try:
    print("\nPlease rate the quality of this summary (1–5):")
    score_input = input("Your score: ")
    if score_input.strip():
        score = int(score_input)
        if 1 <= score <= 5:
            feedback_manager.apply_feedback(score)
            print("Thank you! The agent has updated its internal policy.\n")
        else:
            print("Score must be between 1 and 5. Skipping feedback.\n")
    else:
        print("No score provided. Skipping feedback.\n")
except ValueError:
    print("Invalid input. Skipping feedback.\n")

"""## 13. Notes for Instructor (Project Requirements Mapping)

- **Agent Architecture**  
  - Input Processing: `SafetyModule.validate` and query handling in `IntellectusAgent.run`  
  - Memory System: ChromaDB vector store (`collection`), plus in-memory feedback history  
  - Reasoning Component: ReAct-style loop with Thought → Action → Observation  
  - Output Generation: Structured `report` dictionary with sources and summary  

- **Tool Integration**  
  - Tool 1: WebSearchTool using `duckduckgo-search`  
  - Tool 2: DocumentReaderTool using `requests` + `BeautifulSoup`  
  - Both tools include error handling and their outputs are interpreted by the agent  

- **Reinforcement Learning Elements**  
  - Feedback mechanism: `FeedbackManager.apply_feedback(score)`  
  - Reward signal: user score (1–5) appended to `history`  
  - Policy improvement: adaptation of `num_search_results` and `num_docs_to_read`  

- **Safety and Security Measures**  
  - Input Validation: `SafetyModule` filters harmful or inappropriate queries  
  - Boundary Enforcement: refusal to handle illegal / self-harm / highly sensitive topics  
  - Fallback Strategies: handling of failed web requests and missing results  
  - Transparency: printed ReAct messages (Thought / Action / Observation) for each step  

"""